### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Xzidental** [namansood/counter-bot#1]
Hi, ive gotten the bot working on my discord server, but i cant interact with it in the server itself

![image](https://github.com/tendstofortytwo/counter-bot/assets/84990483/6e593f41-59d5-45b2-8513-acd9d035f654)

![image](https://github.com/tendstofortytwo/counter-bot/assets/84990483/ade9fa00-e15f-46ad-b1d1-e8cbd82492b6)

**Comment by tendstofortytwo** [comment]
Hi! Have you added the bot to your server?

**Comment by Xzidental** [comment]
Yes, i have. the bot was up and running but nothing

**Comment by tendstofortytwo** [comment]
hmm, weird. It should appear as a command, not a message, like so:
![image](https://github.com/tendstofortytwo/counter-bot/assets/5107795/a2272b1f-8bbd-4d4a-8e9c-8ce00ad2e4e2)
Can you try DMing the bot and see if the command shows up there?

**Comment by tendstofortytwo** [comment]
Also, did you run `register.js` first? You need to do that the first time to create the commands, and then `index.js` associates those previously-created commands with its code. If you didn't run `register.js`, the command won't show up.

**Comment by Xzidental** [comment]
I've gotten it working now. Was something on my end. 
Now i do need to know how to create a timer :p

**Comment by tendstofortytwo** [comment]
Good luck with that 😅
